BOS-16 Environment
Bossanity/cards-against-bossanity pull request #4
Opened 2022-02-09 21:29 UTC by Gazyn

New features in this branch: window scaling, obstacles, obstacle functionality, generated tileset, diagonal shooting, damage flashing and unit collision damage

feel free to test those :)
or don't

2022-02-24 17:02 UTC, KarlaYEP2 commented
don't mind this

2022-02-24 17:02 UTC, KarlaYEP2 requested changes
Okay sir, so add some functionality on the obstacle, where some projectiles go through and some don't.
PS I also noticed a bug, when I'm dead I can still shoot.
Thank you :)

2022-03-11 08:54 UTC, Gazyn commented
hello sir i added all the stuff you wanted is this good
[i know discarding isn't part of environment but i planned commits poorly :)]

2022-03-11 10:44 UTC, KarlaYEP2 approved these changes

2022-03-11 10:45 UTC, merged